# -*- coding: utf-8 -*-
"""pregunto2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iwYLroaZr7WAVAG7RXl2WbA3n3VLh-rd
"""

def usuario():  # define la función llamada usuario
    nombre = input("Por favor ingrese su nombre: ")  #
    print(f"Hola, {nombre}! Encantado de conocerte.")
    print()
    print(f"¿En qué te puedo ayudar, {nombre}?")

usuario()